{{- if (eq "" .Values.settings.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chain-view.fullname" . }}-config
type: Opaque
stringData:
  {{- toYaml .Values.settings.config | nindent 2 }}
{{- end -}}